// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersionAttribute("1.4.2.0")]
[assembly: AssemblyFileVersionAttribute("1.4.2.0")]
[assembly: AssemblyProductAttribute("Vimium")]
[assembly: AssemblyCopyrightAttribute("Copyright Phi Long Ho")]
[assembly: InternalsVisibleTo("Vimium.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.4.2.0";
    }
}
