// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersionAttribute("1.2.0.0")]
[assembly: AssemblyFileVersionAttribute("1.2.0.0")]
[assembly: AssemblyProductAttribute("Vimium")]
[assembly: AssemblyCopyrightAttribute("Copyright Zachary Sims")]
[assembly: InternalsVisibleTo("Vimium.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.0.0";
    }
}
